# Generated by Django 6.0.6 on 2026-06-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на регистрацию')),
                ('start_date', models.DateField(verbose_name='Начало регистрации')),
                ('end_date', models.DateField(verbose_name='Конец регистрации')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления на сайт')),
                ('target_audience', models.CharField(choices=[('school', 'Школьник'), ('student', 'Студент')], max_length=10, verbose_name='Целевая аудитория')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Класс (для школьников)')),
                ('stage', models.CharField(choices=[('municipal', 'Муниципальный'), ('regional', 'Региональный'), ('all_russia', 'Всероссийский')], max_length=20, verbose_name='Этап')),
                ('format', models.CharField(choices=[('online', 'Заочно (онлайн)'), ('offline', 'Очно')], max_length=10, verbose_name='Формат')),
                ('region', models.CharField(default='Россия', max_length=100, verbose_name='Регион')),
            ],
        ),
    ]
