# Generated by Django 6.0.6 on 2026-06-28 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Проверено администратором'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='target_audience',
            field=models.CharField(choices=[('school', 'Школьник'), ('student', 'Студент')], max_length=10, verbose_name='Аудитория'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.olympiad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, upload_to='profiles/', verbose_name='Фото')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион проживания')),
                ('show_region', models.BooleanField(default=False, verbose_name='Показывать регион всем')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
