# Generated by Django 6.0.6 on 2026-06-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bannedword_olympiad_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бан до'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True, verbose_name='Причина бана'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
