# Generated by Django 6.0.6 on 2026-06-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesetting_profile_ban_end_date_profile_ban_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, upload_to='themes/', verbose_name='Обложка сайта (фото)')),
            ],
        ),
        migrations.AddField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание олимпиады'),
        ),
    ]
