# Generated by Django 6.0.6 on 2026-06-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customtheme_olympiad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='btn_color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='cookies_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на Cookies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pd_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на ПДн'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_last_login',
            field=models.BooleanField(default=False, verbose_name='Показывать время входа'),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='themes/'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='format',
            field=models.CharField(choices=[('online', 'Заочно (онлайн)'), ('offline', 'Очно')], max_length=10),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='region',
            field=models.CharField(default='Россия', max_length=100),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='stage',
            field=models.CharField(choices=[('municipal', 'Муниципальный'), ('regional', 'Региональный'), ('all_russia', 'Всероссийский')], max_length=20),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='target_audience',
            field=models.CharField(choices=[('school', 'Школьник'), ('student', 'Студент')], max_length=10),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_region',
            field=models.BooleanField(default=False),
        ),
    ]
