# Generated by Django 6.0.6 on 2026-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customtheme_btn_color_customtheme_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='background_color',
            field=models.CharField(default='#eef6fb', max_length=7),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='background_gif',
            field=models.ImageField(blank=True, upload_to='themes/gifs/'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='card_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Дополнительный CSS для оригинальной темы'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='font_family',
            field=models.CharField(blank=True, default='Inter', max_length=120),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='themes/heroes/'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='muted_color',
            field=models.CharField(default='#657786', max_length=7),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='primary_color',
            field=models.CharField(default='#229ED9', max_length=7),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='btn_color',
            field=models.CharField(default='#229ED9', max_length=7),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='text_color',
            field=models.CharField(default='#17212b', max_length=7),
        ),
    ]
