# Generated by Django 6.0.6 on 2026-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customtheme_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='gif_overlay_opacity',
            field=models.CharField(default='0.35', max_length=4, verbose_name='Затемнение/осветление поверх GIF'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='gif_position',
            field=models.CharField(choices=[('center center', 'По центру'), ('center top', 'Сверху по центру'), ('center bottom', 'Снизу по центру'), ('left center', 'Слева по центру'), ('right center', 'Справа по центру')], default='center center', max_length=20, verbose_name='Позиция GIF'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='gif_size',
            field=models.CharField(choices=[('contain', 'Показывать GIF полностью'), ('cover', 'Заполнить весь экран'), ('100% auto', 'Растянуть по ширине'), ('auto 100%', 'Растянуть по высоте')], default='contain', max_length=20, verbose_name='Размер GIF'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='text_outline_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет обводки текста'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='text_outline_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить обводку текста'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='text_outline_strength',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Толщина обводки текста'),
        ),
    ]
