# Generated by Django 6.0.6 on 2026-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customtheme_gif_overlay_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='anime_bg_color',
            field=models.CharField(default='#fff3f8', max_length=7, verbose_name='Фон (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_card_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Цвет карточек (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_card_transparency',
            field=models.CharField(default='0.86', max_length=4, verbose_name='Прозрачность карточек (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_gif_overlay_opacity',
            field=models.CharField(default='0.40', max_length=4, verbose_name='Пелена поверх GIF (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_gif_position',
            field=models.CharField(choices=[('center center', 'По центру'), ('center top', 'Сверху по центру'), ('center bottom', 'Снизу по центру'), ('left center', 'Слева по центру'), ('right center', 'Справа по центру')], default='center center', max_length=20, verbose_name='Позиция GIF (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_gif_size',
            field=models.CharField(choices=[('contain', 'Показывать GIF полностью'), ('cover', 'Заполнить весь экран'), ('100% auto', 'Растянуть по ширине'), ('auto 100%', 'Растянуть по высоте')], default='cover', max_length=20, verbose_name='Размер GIF (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_hero_opacity',
            field=models.CharField(default='0.18', max_length=4, verbose_name='Прозрачность картинки-героя (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_muted_color',
            field=models.CharField(default='#8b6577', max_length=7, verbose_name='Вторичный текст (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_primary_color',
            field=models.CharField(default='#ff7fb3', max_length=7, verbose_name='Акцент (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_text_color',
            field=models.CharField(default='#35222d', max_length=7, verbose_name='Текст (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='anime_use_gif',
            field=models.BooleanField(default=False, verbose_name='Использовать GIF как фон (аниме)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='card_transparency',
            field=models.CharField(default='1.0', max_length=4, verbose_name='Прозрачность карточек (оригинальная)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='gif_card_transparency',
            field=models.CharField(default='1.0', max_length=4, verbose_name='Прозрачность карточек (GIF-тема)'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='metallic_text',
            field=models.BooleanField(default=False, verbose_name='Металлик-серый текст'),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='gif_overlay_opacity',
            field=models.CharField(default='0.35', max_length=4, verbose_name='Белая пелена поверх GIF'),
        ),
    ]
