# Generated by Django 6.0.6 on 2026-06-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_admin_theme_online_chat_improvements'),
        ('main', '0010_alter_customtheme_anime_gif_size_and_more'),
    ]

    operations = [
    ]
