# Generated by Django 6.0.6 on 2026-06-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20260629_2032'),
        ('main', '0011_olympiad_codes_unified_card_theme'),
    ]

    operations = [
    ]
