# Generated by Django 6.0.6 on 2026-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20260630_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtheme',
            name='business_card_transparency',
            field=models.CharField(default='0.62', max_length=4, verbose_name='Прозрачность карточек деловой темы'),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='gif_card_transparency',
            field=models.CharField(default='0.72', max_length=4, verbose_name='Прозрачность карточек (GIF-тема)'),
        ),
    ]
