# Generated by Django 6.0.6 on 2026-06-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_dynamic_theme_presets_brand_sound'),
        ('main', '0013_alter_customtheme_business_card_transparency_and_more'),
    ]

    operations = [
    ]
