# Generated by Django 6.0.6 on 2026-06-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_theme_overlay_sounds_admin_media'),
        ('main', '0014_merge_20260630_0111'),
    ]

    operations = [
    ]
