# Generated by Django 6.0.6 on 2026-06-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_favorites_comment_admin_controls_sound_volume'),
        ('main', '0015_merge_20260630_0140'),
    ]

    operations = [
    ]
