# Generated by Django 6.0.6 on 2026-06-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_olympiad_short_description'),
        ('main', '0016_merge_20260630_0245'),
    ]

    operations = [
    ]
