# Generated by Django 6.0.6 on 2026-06-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20260630_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
    ]
